services:
  authentication:
    build:
      context: .
      dockerfile: authentication/Dockerfile
    ports:
      - '8101:8000'
    volumes:
      - ./authentication:/authentication

  client_1:
    build:
      context: .
      dockerfile: client_1/Dockerfile
    ports:
      - '8102:8000'
    volumes:
      - ./client_1:/client

  client_2:
    build:
      context: .
      dockerfile: client_2/Dockerfile
    ports:
      - '8103:8000'
    volumes:
      - ./client_2:/client

